name: Code Quality

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  format-check:
    name: Check Code Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check code formatting
        run: npm run format:check

      - name: Display formatting success
        run: |
          echo "✅ Code formatting is consistent"
        if: success()

      - name: Display formatting issues
        run: |
          echo "❌ Code formatting issues found"
          echo "Run 'npm run format' to fix formatting issues"
          exit 1
        if: failure()
