name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Run tests with coverage
        run: npm run test:coverage
        if: matrix.node-version == '20.x'

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: matrix.node-version == '20.x'
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7

      - name: Display test results
        run: |
          echo "✅ Tests completed successfully on Node.js ${{ matrix.node-version }}"
        if: success()

      - name: Display test failure
        run: |
          echo "❌ Tests failed on Node.js ${{ matrix.node-version }}"
          exit 1
        if: failure()
